### ISSUE TITLE
Blank container in 3.5 update

### ISSUE THREAD

**Issue by benjordan** [fhuel/Unsplash-It-Sketch#11]
I updated to Sketch 3.5 today and now the plugin is no longer working. I select the shape, hit the shortcut, and the container goes white and there is no fill.

Not sure if it is 100% related to the new version, but it is consistently not working which makes me sad, since this is one of mt favorite plugins.

**Comment by fhuel** [comment]
there was an issue with the 3.5 update, but it should work fine now. Try to download the plugin again ;)

**Comment by benjordan** [comment]
Awesome! Thanks. Working now.

**Comment by fhuel** [comment]
great :)
