### ISSUE TITLE
Not working anymore witch Sketch 3.5

### ISSUE THREAD

**Issue by KadirKara** [fhuel/Unsplash-It-Sketch#12]
I guess it’s not working anymore with the new version of sketch. It just turns the rectangle white unfortunately.

**Comment by fhuel** [comment]
yes, there was an issue with the 3.5 . The plugin should work fine now

**Comment by whale** [comment]
Thank you for fixing it. This is a champ plugin.

**Comment by fhuel** [comment]
Hey Matthew, thanks! Glad you find it useful
