### ISSUE TITLE
Does not work in Sketch 3.6

### ISSUE THREAD

**Issue by xavez** [fhuel/Unsplash-It-Sketch#13]
Plugin does not work anymore with the latest version of Sketch. When I generate, all I get is a white rectangle.

**Comment by fhuel** [comment]
Hey @xavez , thank you for letting me know of this issue. 
I just tested on 3.6.1 and everything seems to work fine. Are you sure you have the latest version of the plugin ?

**Comment by xavez** [comment]
@fhuel super strange, when I clone the github repo into my plugins folder (which used to work) it doesn’t work anymore. When I download the zip file and double-click the `.sketchplugin` file, it does work. Seems like Sketch changed something about the way plugins work. Anyway, thanks for putting me on the right path to investigate :-)

**Comment by fhuel** [comment]
@xavez yeah, that's strange indeed, I'll look into it. Anyway, I'm glad the plugin is working fine for you now. Thanks again for letting me know about this issue
