### ISSUE TITLE
Crashes Sketch

### ISSUE THREAD

**Issue by carynnireland** [fhuel/Unsplash-It-Sketch#15]
Plugin crashes Sketch every time I try to use it. Using Sketch Version 3.8.3 (29802).

**Comment by onmyway133** [comment]
I have crashes as well 😢

**Comment by controversial** [comment]
Same here. Any ideas @fhuel ?

**Comment by carynnireland** [comment]
I couldn't get it to stop crashing and started using craft manager instead, it utilizes unsplash.

**Comment by fhuel** [comment]
hey, sorry for the delay, it works fine now
