### ISSUE TITLE
Low image quality

### ISSUE THREAD

**Issue by pugson** [fhuel/Unsplash-It-Sketch#24]
I wish there was a way to specify what size of images should be downloaded. Right now the quality does not look that good in @1x.

I made [a fork](https://github.com/dubstrike/Unsplash-It-Sketch/releases/tag/1.4.1) that downloads images 3x larger than the layer size.

**Comment by fhuel** [comment]
Thank you @dubstrike , 
3x images should be a bit slower to download, but I don't think it would make too much of a difference,  at least if you are not behind a slow connection. (did you noticed any difference? )

Also, even if someone decides to use the images in their final design they'll have to re-export them anyway I guess, and 3x I presume is the maximum "oversampling" you need even if you design at 1x. 

Great.
Well, if you prefer you can make a pull request and have your edits included, else, good job mate ;)

**Comment by pugson** [comment]
It did take an extra second or two to download (depending on the layer size) but looked much better. It also made everything more flexible, since you could change the layer size without losing much quality or having to replace the photo.

I'm worried about downloading 50mb images if you decide to fill a large layer — like a desktop full-size cover. They would really bloat the document. Perhaps a quality setting would make most sense before this change is released.

Check out how the Confetti plugin handles user settings.
[confetti.sketchplugin.zip](https://github.com/fhuel/Unsplash-It-Sketch/files/980882/confetti.sketchplugin.zip)
