### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by pugson** [fhuel/Unsplash-It-Sketch#27]
Just updated the plugin and the settings option doesn't do anything. Here's the log from Console.app:

```
default	21:32:09.639269 +0200	Sketch	*** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/AppKit.subproj/NSCell.m:1674
default	21:32:09.640636 +0200	Sketch	Exception: Invalid parameter not satisfying: aString != nil
default	21:32:09.640727 +0200	Sketch	Invalid parameter not satisfying: aString != nil
```

I'm using Sketch 44.1 and macOS 10.12.5.

**Comment by fhuel** [comment]
Ok, thank you for the feedback!
I'll take a look

**Comment by mediashock** [comment]
The plugin is pretty sweet, but I am having this issue as well. :(

**Comment by fhuel** [comment]
Ok, I think I found the problem. 
The fix is on the list.

Thank you guys for letting me know

**Comment by fhuel** [comment]
Thought I was on the right path, but I wasn't. Need more time to find the reasons of this bug.
Help would be highly welcome ;)
