### ISSUE TITLE
If multiple shapes are selected, different photos should be used.

### ISSUE THREAD

**Issue by adampatterson** [fhuel/Unsplash-It-Sketch#30]
I selected two rectangles and got the same photo for both.

A side but related issue is that I could not select the image and apply a new image to it. I get an error along the lines of needing a vector shape.

**Comment by fhuel** [comment]
Hi @adampatterson , thanks for your feedback.

1) You are definitely right. It should use different photos, and that is the way it was working, so I presume is a bug included in the latest update. If not a change of the Unsplash API. I'll look into it, thanks.

2) Currently the plugin works only on Shape Layers ( "primitives" that you can find in the menu  Insert > Shape ). Maybe this is the error you got? Also you cannot mess too much with the point in the shape layer and then run the plugin.  It's something I would like to improve though
