### ISSUE TITLE
Weird performance

### ISSUE THREAD

**Issue by malykh** [fhuel/Unsplash-It-Sketch#6]
Hi! I love your plug-in, thank you. However I'm having some issues now. It worked fine at first, but now, when I click unsplash it, nothing happens. I have to restart the sketch, then it works again only for 3-4 times. 

Sketch 3.4.2

**Comment by fhuel** [comment]
Hey Malykh, 
glad you find the plugin useful,
thank you for letting me know about this issue.

When it happens, does Sketch crashes, freezes, or just does nothing and you reboot the app yourself? 
( this is just to be sure but ) are you selecting a shape before running the plugin?

Could you please also tell me the OsX version you are using?

Thanks

**Comment by malykh** [comment]
@fhuel Thanks for quick respond!
I just noticed: this only happens when I have multiple sketch files open. Seems like plug-in generates results in another not-active window. When I close all other files, plug-in works fine again. 

Im on Mac OS X 10.10.5

**Comment by fhuel** [comment]
oh, that's weird...
I'll look into it,
thanks!

**Comment by nolastan** [comment]
This seems to be a new issue with Sketch affecting other plugins as well :cry: 
https://github.com/ddwht/sketch-dynamic-button/issues/28

**Comment by fhuel** [comment]
Well, this could actually be seen as relatively good news. Meaning that it's a shared issue and the guys at Bohemian coding will probably fix it.
That being said, I'm not able to replicate the issue and investigate on the causes ... seems to work fine for me even with several Sketch files opened. Have you tried @nolastan ?

**Comment by nolastan** [comment]
No I can't reproduce either.

**Comment by malykh** [comment]
@fhuel ok thanks, good to know. Hoping they will fix that soon.
