### ISSUE TITLE
Unsplash It with Options not Available

### ISSUE THREAD

**Issue by chinovian** [fhuel/Unsplash-It-Sketch#7]
Sketch v3.4.4
Unsplash It v1.3

![unsplash_w_options_missing](https://cloud.githubusercontent.com/assets/1257953/11985948/f60f7458-a997-11e5-977e-e689b448f854.jpg)

**Comment by fhuel** [comment]
Using the official API you can now use tags in layers name to fetch only pictures related to those tags, but moving to the Unsplash.com official API made it impossible to keep the  + options version as it was. 
This was the reason I decided to remove the  + options version, at least temporary. 
Also those treatments on the picture are relatively easy to obtain with Sketch itself.
I'm anyway looking for a good way to restore those options if needed.
