### ISSUE TITLE
Unsplash with Options not showing

### ISSUE THREAD

**Issue by susanbartolme** [fhuel/Unsplash-It-Sketch#8]
Under Plugins --> Unsplash It Sketch there is no sub menu for Unsplash with options. 
All I see is

Plugins -->  Unsplash It Sketch --> Unsplash it

I've tried uninstalling and installing again. Any ideas?

**Comment by fhuel** [comment]
Hi, 
yeah, that option is no longer available. I realize that the clip is outdated and confusing. Needs to be changed, sorry about that.
Using the official API you can now use tags in layers name to fetch only pictures related to those tags, but moving to the Unsplash.com official API made it impossible to keep the + options version as it was. 
This was the reason why has been decided to remove the + options version, at least temporary. 
Also those treatments on the picture are relatively easy to obtain with Sketch itself.
I'm anyway looking for a good way to restore those options if needed.
