### ISSUE TITLE
Result = white rect. Possible conflict with Sketch 3.5 update?

### ISSUE THREAD

**Issue by oliverfoggin** [fhuel/Unsplash-It-Sketch#9]
I just installed this after reading about it in this tutorial...

https://medium.com/sketch-app-sources/designing-an-ios-app-in-sketch-part-1-of-3-7541f4fca87a#.4f08oqsnm

But when I select the rect and choose "Unsplash It" I'm just left with a white rect. If I put a background colour on the rect and then Unsplash It it just becomes white again.

No crash that I can see. Just a white rect.

Installed from Sketch Toolbox
Sketch 3.5
OS X El Capitan 10.11.2

Thanks

**Comment by fhuel** [comment]
Hey, thank you for letting me know.
I just installed the 3.5 after reading this, and it does the exactly same thing here.
Trying to understand the reason...

**Comment by marcusandrew** [comment]
Hey Manuele,

I noticed the same issue was happening with https://github.com/timuric/Content-generator-sketch-plugin Timur seems to have fixed the issue with his plugin. Worth having a chat with him? https://twitter.com/timur_carpeev

thanks

**Comment by fhuel** [comment]
Hey @marcusandrew ,
yeah Timur helped with a very timely pull request! Everything works again now :)
